### ISSUE TITLE
Merge all organizations into HolismHolding

### ISSUE THREAD

**Issue by Nefcanto** [HolismHolding/Issues#149]
Now that we have improved the semantics about org, repo, module, and app, it's time to merge all codebases into a single organization for more convenience.

**Comment by 20Amir01** [comment]
The `HolismProject` organization and `Holism` repo still exist<br/>
When I enter this command : `Org HolismProjects` the terminal screen closes and after that I get a ‍‍‍‍‍‍‍‍`permission denied` error in Docker, after which I have to enter the following commands every time to solve the problem :
```
sudo gpasswd -a $USER docker
newgrp docker
sudo groupadd docker
sudo usermod -aG docker ${USER}
sudo usermod -aG docker $USER
```

**Comment by Nefcanto** [comment]
@20Amir01, `HolismProjects` is not a base organization. We merged all base organizations into `HolismHolding`.

I didn't understand your second problem.
