### ISSUE TITLE
Setup not working

### ISSUE THREAD

**Issue by maryamt1991** [HolismHolding/Issues#173]
did you changed Setup Command? I get this error
![Screenshot from 2024-04-24 07-17-40](https://github.com/HolismHolding/Issues/assets/108225295/8c820c66-7ab5-4975-9d39-2cffbc353de8)
i cloned commands manually but there isn't Setup in it.

**Comment by hosseinitabar** [comment]
@maryamt1991, it's renamed to `Start`. That makes more send. `Start/Stop`.
