### ISSUE TITLE
RecloneHolism command error

### ISSUE THREAD

**Issue by ghazaleaghaei** [HolismHolding/Issues#184]
I used the following script to get the holism, 

`sudo mkdir /HolismHolding`
`sudo chmod 777 /HolismHolding`
 `cd /HolismHolding`
`git clone git@github.com:HolismHolding/Commands`
`git clone git@github.com:HolismHolding/Scripts`
`git clone git@github.com:HolismHolding/Setup`
`Install`
`Update`
`RecloneHolism`

but after running the `RecloneHolism` command, I get these errors. 

![Screenshot from 2024-05-08 11-08-13](https://github.com/HolismHolding/Issues/assets/95690607/5ad0c5ff-9e14-4887-9c92-443249a2eb8b)

Where did I go wrong?

**Comment by hosseinitabar** [comment]
Your packages are incompletely installed
Do the Install command again with Shecan and without its or alternate DNS of 403.online
You can switch between DNS with this command:
```
ChangeDns
```

And also don't forget to save the GitHub PAT (Personal Access Token) in this file:
```
/LocalSecrets/GitHubAccessToken
```

Also, your VS Code should be synced with your GitHub

**Comment by ghazaleaghaei** [comment]
Thankyou
